### ISSUE TITLE
parse 문제 같은데 왜일까요 ㅜㅜ

### ISSUE THREAD

**Issue by hellobk1231** [naver/lucy-xss-servlet-filter#46]
오류콘솔 일부만 올려봅니다..
필터 [xssEscapeServletFilter]을(를) 시작하는 중 오류 발생
java.lang.ExceptionInInitializerError
at com.navercorp.lucy.security.xss.servletfilter.XssEscapeFilter.<clinit>(XssEscapeFilter.java:38)
	at com.navercorp.lucy.security.xss.servletfilter.XssEscapeServletFilter.<init>(XssEscapeServletFilter.java:28)
caused by
Cannot parse the RequestParam configuration file [lucy-xss-servlet-filter-rule.xml].
적어도 하나의 JAR가 TLD들을 찾기 위해 스캔되었으나 아무 것도 찾지 못했습니다.

다른 부분과의 충돌? bean설정? 톰캣lucy 연동문제?
도무지 감을 못잡겠습니다...

jar파일은 다 확인됩니다
lucy-xss-servlet-2.0.0.0 jar
commons-lang3-3.3.2.jar
commons-logging-1.1.1.jar
lucy-xss-1.6.3.jar

web.xml에서 encodingfilter 뒤에 lucy필터 적용했구요 ㅜㅜ

**Comment by hellobk1231** [comment]
d

**Comment by hellobk1231** [comment]
ㅜㅜgit처음 사용해봐서 issue삭제 부탁드립니다..
